src/objects/ptContact__c.object
<CustomObject>
    <description>Custom objects to Contacts from Vendors and Consumers</description>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>ptContacts</relationshipLabel>
        <relationshipName>ptContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ptContact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ptContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor__c.object
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ptNewVendorWizardController.cls
public with sharing class ptNewVendorWizardController {
    Vendor__c ptVendor;
    ptContact__c ptContact;
    
    public Vendor__c getptVendor() {
        if (ptVendor == null)
            ptVendor = new Vendor__c();
            
        return ptVendor;
    }
    
    public ptContact__c getptContact() {
        if(ptContact == null)
            ptContact = new ptContact__c();
            
        return ptContact;           
    }
    
    public PageReference step1() {
        return Page.ptNewVendorStep1;
        
    }
    
    public PageReference step2() {
        return Page.ptNewVendorStep2;
    }
    
    public PageReference step3() {
        return Page.ptNewVendorStep3;
    }
    
    public PageReference save() {
    	try {
        	insert ptVendor;
    	} catch (Exception e) {
    		PageReference p = Page.ptVendorThankYou;
    		p.getParameters().put('error', 'noInsert');
    	}
        ptContact.Vendor__c = ptVendor.id;
        
        try {
        	insert ptContact;
        } catch (Exception e) {
        	PageReference p = Page.ptVendorThankYou;
        	p.getParameters().put('error', 'noInsert');   
        	     
        }
        
        PageReference p = Page.ptVendorThankYou;
                
        p.setRedirect(true);
        return p;
    }
    
    
}